global_techs = {
"AdvancedFissionSystems": 25000,
"AdvancedMagnetics": 1000,
"AntimatterContainment": 35000,
"AntimatterMassProduction": 60000,
"AntimatterPropulsion": 60000,
"CleanEnergy": 50000,
"DeuteriumDeuteriumFusion": 50000,
"DeuteriumHelium3Fusion": 50000,
"DeuteriumTritiumFusion": 30000,
"ElectromagneticPropulsion": 2500,
"ElectrostaticPlasmaConfinement": 15000,
"ElectrostaticPropulsion": 2500,
"ElectrothermalPropulsion": 2500,
"FutureTechEnergy": 100000,
"GasCoreFissionSystems": 20000,
"HighEnergyElectromagneticPropulsion": 5000,
"HighEnergyElectrostaticPropulsion": 5000,
"HighEnergyElectrothermalPropulsion": 5000,
"HighEnergyLasers": 1000,
"HydrogenLithium6Fusion": 30000,
"InertialPlasmaConfinementTechniques": 35000,
"MagneticForceManipulation": 2500,
"MagneticNozzles": 25000,
"MagneticPlasmaConfinementTechniques": 30000,
"MassDrivers": 1000,
"MoltenCoreFissionSystems": 10000,
"NeutroniumContainment": 25000,
"NuclearFissioninSpace": 2500,
"NuclearFusioninSpace": 25000,
"PhasedArrayLasers": 70000,
"ProtonBoronFusion": 40000,
"ProtonProtonFusion": 95000,
"SolidCoreFissionSystems": 5000,
"TerawattFusionReactors": 95000,
"VacuumElectrostaticPrinciples": 1000,
"ZPinchTechniques": 15000,
"AdvancedAtomicManipulation": 10000,
"AdvancedCarbonManipulation": 1000,
"AdvancedChemicalRocketry": 1000,
"AdvancedHydrogenContainment": 20000,
"AdvancedSuperconductors": 3500,
"CarbonNanotubes": 3500,
"Diamondoids": 15000,
"FissionPulseDrives": 25000,
"FutureTechMaterials": 100000,
"HeavyPulsedPropulsion": 50000,
"HighTemperatureSuperconductors": 35000,
"ImprovedShipbuildingTechniques": 20000,
"MolecularAssemblers": 20000,
"NextGenerationAerospace": 5000,
"OrbitalShipbuilding": 1000,
"Supercapacitors": 10000,
"SuperconductingMagnets": 10000,
"TitanicSpacecraft": 60000,
"Ultracapacitors": 40000,
"AdministrationAlgorithms": 30000,
"AdvancedNeuralNetworks": 5000,
"AppliedArtificialIntelligence": 25000,
"AugmentedReality": 1500,
"Cybernetics": 5000,
"FutureTechInformationScience": 100000,
"NetworkedPropaganda": 10000,
"PhotonicComputing": 1500,
"QuantumComputing": 10000,
"QuantumEncryption": 20000,
"SelfRepairingSoftware": 10000,
"WhiteCollarAutomation": 40000,
"ArrivalPsychology": 5000,
"Biotechnology": 1500,
"ColonyHabs": 35000,
"DesignerLifeforms": 30000,
"ExtendedSpaceSurvival": 5000,
"FutureTechLifeScience": 100000,
"Genies": 50000,
"MindandMachine": 35000,
"OrbitalRingHabs": 5000,
"OrbitalTorusHabs": 35000,
"OutpostHabs": 1000,
"PredictiveGenetics": 5000,
"SettlementHabs": 5000,
"SpaceAgriculture": 2500,
"SpaceMedicine": 2500,
"TransformPhages": 10000,
"AdvancedMissileWarfareDoctrine": 20000,
"AntimatterWeaponry": 70000,
"ArcLasers": 25000,
"ClimateChangeMitigation": 100000,
"ArrivalSecurity": 10000,
"Coilguns": 30000,
"DirectedEnergyWarfareDoctrine": 2500,
"FutureTechMilitaryScience": 100000,
"InfraredCombatLasers": 5000,
"KineticsWarfareDoctrine": 2500,
"MilitarizationofSpace": 5000,
"MissileWarfareDoctrine": 2500,
"NetworkedGlobalDefense": 25000,
"ParticleCannon": 5000,
"PlasmaWeapons": 40000,
"PrinciplesofSpaceWarfare": 1000,
"Railguns": 5000,
"SpaceAssaultDoctrine": 10000,
"TargetedBiologicalWarfare": 30000,
"TerrestrialMilitaryScience": 3000,
"TransInterfaceWarfare": 25000,
"UltravioletCombatLasers": 60000,
"VisibleCombatLasers": 25000,
"Accelerando": 50000,
"AdAstra": 5000,
"ArrivalCulture": 20000,
"ArrivalDomesticPolitics": 2000,
"ArrivalEconomics": 2500,
"ArrivalGovernance": 35000,
"ArrivalInternationalDevelopment": 5000,
"ArrivalInternationalRelations": 5000,
"ArrivalLaw": 5000,
"ArrivalMassCommunications": 5000,
"ArrivalSociology": 2500,
"DirectedSpaceResearch": 5000,
"FallofEmpires": 10000,
"FleetLogistics": 45000,
"FutureTechSocialScience": 100000,
"GreatNations": 25000,
"IndependenceMovements": 5000,
"IndustrializationofSpace": 15000,
"IntegratedEarthSpaceEconomy": 40000,
"InterplanetaryPolities": 50000,
"OurSpaceFuture": 30000,
"SpaceCommerce": 20000,
"SpaceResearch": 2500,
"SpaceTourism": 1000,
"UnityMovements": 10000,
"WeAreNotAlone": 500,
"AdvancedHeatManagementConcepts": 2500,
"DeepSpacePropulsionConcepts": 1000,
"DeepSystemSkywatch": 1000,
"FutureTechSpaceScience": 100000,
"InSituResourceUtilization": 5000,
"MissionToJupiter": 10000,
"MissionToMars": 2500,
"MissionToSaturn": 25000,
"MissionToSpace": 250,
"MissionToTheAsteroids": 3500,
"MissiontotheInnerPlanets": 15000,
"MissiontotheMoon": 1000,
"MissiontotheOuterPlanets": 40000,
"Skywatch": 250,
"SpaceMiningandRefining": 2500,
"Tokamaks": 25000,
"AneutronicFusion": 75000
}

tech_list = ["AdvancedFissionSystems", "AdvancedMagnetics", "AntimatterContainment", "AntimatterMassProduction", "AntimatterPropulsion", "CleanEnergy", "DeuteriumDeuteriumFusion", "DeuteriumHelium3Fusion", "DeuteriumTritiumFusion", "ElectromagneticPropulsion", "ElectrostaticPlasmaConfinement", "ElectrostaticPropulsion", "ElectrothermalPropulsion", "FutureTechEnergy", "GasCoreFissionSystems", "HighEnergyElectromagneticPropulsion", "HighEnergyElectrostaticPropulsion", "HighEnergyElectrothermalPropulsion", "HighEnergyLasers", "HydrogenLithium6Fusion", "InertialPlasmaConfinementTechniques", "MagneticForceManipulation", "MagneticNozzles", "MagneticPlasmaConfinementTechniques", "MassDrivers", "MoltenCoreFissionSystems", "NeutroniumContainment", "NuclearFissioninSpace", "NuclearFusioninSpace", "PhasedArrayLasers", "ProtonBoronFusion", "ProtonProtonFusion", "SolidCoreFissionSystems", "TerawattFusionReactors", "VacuumElectrostaticPrinciples", "ZPinchTechniques", "AdvancedAtomicManipulation", "AdvancedCarbonManipulation", "AdvancedChemicalRocketry", "AdvancedHydrogenContainment", "AdvancedSuperconductors", "CarbonNanotubes", "Diamondoids", "FissionPulseDrives", "FutureTechMaterials", "HeavyPulsedPropulsion", "HighTemperatureSuperconductors", "ImprovedShipbuildingTechniques", "MolecularAssemblers", "NextGenerationAerospace", "OrbitalShipbuilding", "Supercapacitors", "SuperconductingMagnets", "TitanicSpacecraft", "Ultracapacitors", "AdministrationAlgorithms", "AdvancedNeuralNetworks", "AppliedArtificialIntelligence", "AugmentedReality", "Cybernetics", "FutureTechInformationScience", "NetworkedPropaganda", "PhotonicComputing", "QuantumComputing", "QuantumEncryption", "SelfRepairingSoftware", "WhiteCollarAutomation", "ArrivalPsychology", "Biotechnology", "ColonyHabs", "DesignerLifeforms", "ExtendedSpaceSurvival", "FutureTechLifeScience", "Genies", "MindandMachine", "OrbitalRingHabs", "OrbitalTorusHabs", "OutpostHabs", "PredictiveGenetics", "SettlementHabs", "SpaceAgriculture", "SpaceMedicine", "TransformPhages", "AdvancedMissileWarfareDoctrine", "AntimatterWeaponry", "ArcLasers", "ClimateChangeMitigation", "ArrivalSecurity", "Coilguns", "DirectedEnergyWarfareDoctrine", "FutureTechMilitaryScience", "InfraredCombatLasers", "KineticsWarfareDoctrine", "MilitarizationofSpace", "MissileWarfareDoctrine", "NetworkedGlobalDefense", "ParticleCannon", "PlasmaWeapons", "PrinciplesofSpaceWarfare", "Railguns", "SpaceAssaultDoctrine", "TargetedBiologicalWarfare", "TerrestrialMilitaryScience", "TransInterfaceWarfare", "UltravioletCombatLasers", "VisibleCombatLasers", "Accelerando", "AdAstra", "ArrivalCulture", "ArrivalDomesticPolitics", "ArrivalEconomics", "ArrivalGovernance", "ArrivalInternationalDevelopment", "ArrivalInternationalRelations", "ArrivalLaw", "ArrivalMassCommunications", "ArrivalSociology", "DirectedSpaceResearch", "FallofEmpires", "FleetLogistics", "FutureTechSocialScience", "GreatNations", "IndependenceMovements", "IndustrializationofSpace", "IntegratedEarthSpaceEconomy", "InterplanetaryPolities", "OurSpaceFuture", "SpaceCommerce", "SpaceResearch", "SpaceTourism", "UnityMovements", "WeAreNotAlone", "AdvancedHeatManagementConcepts", "DeepSpacePropulsionConcepts", "DeepSystemSkywatch", "FutureTechSpaceScience", "InSituResourceUtilization", "MissionToJupiter", "MissionToMars", "MissiontoSaturn", "MissionToSpace", "MissionToTheAsteroids", "MissiontotheInnerPlanets", "MissionToTheMoon", "MissiontotheOuterPlanets", "Skywatch", "SpaceMiningandRefining", "Tokamaks", "AneutronicFusion"]

jobs = [
"Operative",
"Officer",
"Politician",
"Judge",
"Executive",
"Diplomat",
"TechMogul",
"Scientist",
"Evangelist",
"Professor",
"Astronaut",
"Inspector",
"Rebel",
"Commando",
"Spy",
"Fixer",
"Kingpin",
"Investigator",
"Journalist",
"Hacker",
"Activist",
"Celebrity",
"Tycoon",
"Attorney",
"Engineer"
]

traits = [
"Government",
"Transparent",
"Apocalyptic",
"Aware",
"HardTarget",
"Streetwise",
"Veteran",
"Vengeful",
"QuickLearner",
"Striver",
"Survivor",
"Crew",
"Counselor",
"Unifier",
"Affluent",
"Prosperous",
"Wealthy",
"Astronomer",
"Chemist",
"Doctor",
"Physicist",
"ComputerScientist",
"MilitaryScientist",
"SocialScientist",
"SeniorAstronomer",
"SeniorChemist",
"SeniorDoctor",
"SeniorPhysicist",
"SeniorComputerScientist",
"SeniorMilitaryScientist",
"SeniorSocialScientist",
"ChiefAstronomer",
"ChiefChemist",
"ChiefDoctor",
"ChiefPhysicist",
"ChiefComputerScientist",
"ChiefMilitaryScientist",
"ChiefSocialScientist",
"Connected",
"PuppetMaster",
"LowProfile",
"Undercover",
"Agitator",
"SecondWave",
"PherocyteEmitter",
"PherocyteMassEmitter",
"Firebrand",
"Demagogue",
"Rich",
"Billionaire",
"Eminent",
"Famous",
"Megastar",
"OpinionLeader",
"MediaDarling",
"ElderStatesman",
"Averse",
"Paranoid",
"Ethical",
"Pacifist",
"Academic",
"AwkwardGenius",
"Brazen",
"ConspiracyTheorist",
"Corrupt",
"Cynic",
"Expert",
"LoneWolf",
"Oligarch",
"NationalHero",
"Suspicious",
"Technocrat",
"Criminal",
"Sociopath",
"Furtive",
"Inscrutable",
"Pollyanna",
"Extremist",
"Fanatic",
"Inflexible",
"Declining",
"Careless",
"Delinuent",
"Addict",
"Earthbound",
"Extorted",
"Indebted",
"Indulgent",
"Pariah",
"EnemyoftheState",
"NonGrata",
"FamilyTies",
"Innovative",
]
